export const ICONS = {
  home: 'ri-home-5-fill',
  user: 'ri-user-5-fill',
  parents: 'ri-group-fill',
  password: 'ri-lock-password-fill',
  email: 'ri-mail-fill',
  phone: 'ri-phone-fill',
  calendar: 'ri-calendar-2-fill',
  location: 'ri-map-pin-2-fill',
  bus: 'ri-bus-2-fill',
  mapPin: 'ri-map-pin-line',
  close: 'ri-close-fill',
  delete: 'ri-delete-bin-5-fill',
  plus: 'ri-add-fill',
  minus: 'ri-subtract-fill',
  excel: 'ri-file-excel-2-fill',
  download: 'ri-download-2-line',
  search: 'ri-search-line',
  sortDesc: 'ri-sort-desc',
  more: 'ri-more-2-line',
  pagerLeft: 'ri-arrow-left-s-line',
  pagerRight: 'ri-arrow-right-s-line',
  expand: 'ri-arrow-down-s-line',
  expandUp: 'ri-arrow-up-s-line',
  menu: 'ri-menu-line',
  subgroup: 'ri-arrow-down-s-fill',
  edit: 'ri-edit-2-fill',
} as const